"""Run M0.1 (corpus split) and the M0.2 gate, writing artifacts under m0/.

    uv run python -m zaspro.m0.run

Stops at the M0.2 gate. M0.3-M0.6 are separate runners, built later.
"""

from __future__ import annotations

import sys
from pathlib import Path

from zaspro.extraction.boilerplate import strip_boilerplate
from zaspro.extraction.corpus import build_corpus_split
from zaspro.extraction.figures import drawing_attribution
from zaspro.extraction.gate import cross_validate
from zaspro.extraction.marking_scheme import parse_marking_scheme
from zaspro.extraction.models import CorpusEntry, ExerciseChunk, SegmentationGateResult
from zaspro.extraction.pandoc_convert import convert_docx_to_latex, pandoc_version
from zaspro.extraction.segment import segment_arkusz

ROOT = Path(__file__).resolve().parents[3]
RAW = ROOT / "sources" / "raw"
MANIFEST = ROOT / "sources" / "MANIFEST.md"
OUT = ROOT / "m0"
WORK = OUT / "_work"  # gitignored pandoc intermediates

ARKUSZ_DOCX = "MMAP-P0-660-A-2605-arkusz.docx"
ZASADY_PDF = "MMAP-P0-100-2605-zasady.pdf"


# --------------------------------------------------------------------------- M0.1


def _fmt(v: object) -> str:
    return "—" if v is None else str(v)


def write_corpus_split(entries: list[CorpusEntry]) -> Path:
    lines = [
        "# M0.1 — Corpus split table",
        "",
        "Generated by `zaspro.m0.run`. For each document in `sources/MANIFEST.md`:",
        "does a structured `_660.docx` sibling exist, and what does the OOXML carry.",
        "",
        "| document | fmt | DOCX sibling | sibling present | oMath | display (oMathPara) | drawings | media | track |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for e in entries:
        lines.append(
            f"| `{e.file}` | {e.fmt} | {('`'+e.docx_sibling+'`') if e.docx_sibling else '—'} "
            f"| {'yes' if e.sibling_present else 'no'} | {_fmt(e.omath)} | {_fmt(e.omath_para)} "
            f"| {_fmt(e.drawings)} | {_fmt(e.media_files)} | {e.track.value} |"
        )
    lines += ["", "## Notes and exceptions", ""]
    for e in entries:
        if e.notes:
            lines.append(f"- `{e.file}`: {e.notes}")
    lines += [
        "",
        "## Comparison to SPEC §2a spike (reconciled)",
        "",
        "Counts here are element counts from `word/document.xml` only (no math in "
        "headers/footers/footnotes), matching `<m:oMath[ >]` and `<m:oMathPara[ >]`, "
        "open/close tags verified balanced. SPEC §2a has been corrected to these "
        "numbers.",
        "",
        "| document | measure | corrected | original §2a |",
        "|---|---|---|---|",
        "| informator | oMath | 994 | 1386 |",
        "| informator | display (oMathPara) | 212 | 392 |",
        "| informator | drawings | 25 | 25 |",
        "| informator | media | 0 | 0 |",
        "| arkusz | oMath | 284 | 298 |",
        "| arkusz | display (oMathPara) | 9 | not measured |",
        "| arkusz | drawings | 18 | 18 |",
        "| arkusz | media | 5 | 5 |",
        "",
        "**Cause.** The original spike counted `<m:oMath` as a raw substring. That "
        "string is a prefix of both `<m:oMathPara` and `<m:oMathParaPr`, so display "
        "equations and paragraph-property elements were counted into the `oMath` "
        "column. Measured raw prefixes: informator `<m:oMath` = 1386, `<m:oMathPara` "
        "= 392 (212 `oMathPara` + 180 `oMathParaPr`); arkusz `<m:oMath` = 298, "
        "`<m:oMathPara` = 14. Old minus new: `1386 − 392 = 994`, `298 − 14 = 284`. "
        "Drawings and media were always exact. No decision or plan item changes.",
    ]
    lines += [
        "",
        "## Marking-scheme sibling check (SPEC M0.1)",
        "",
        f"Derived sibling for `{ZASADY_PDF}` would be "
        "`MMAP-P0-660-2605-zasady.docx`. It is **not present** in `sources/raw/`, "
        "and CKE's naming convention (docs/sources.md A3) publishes `-zasady` only "
        "as PDF. The M0.2 gate therefore reads the marking scheme from the `100` "
        "PDF via `pdftotext -layout` — recorded here as an explicit exception, not "
        "passed over silently.",
        "",
    ]
    path = OUT / "corpus_split.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# --------------------------------------------------------------------------- M0.2


def write_gate_report(
    result: SegmentationGateResult,
    chunks: list[ExerciseChunk],
    strip_summary: str,
    fig_by_task: dict[str, int],
    fig_boilerplate: int,
    fig_total: int,
) -> Path:
    ok = result.passed
    chunk_count = len(chunks)
    parent_count = sum(1 for c in chunks if c.is_parent)
    incomplete = [c for c in chunks if c.figures_incomplete]
    fig_attributed = sum(fig_by_task.values())  # physical drawings, not chunk sums
    fig_regions = sum(1 for v in fig_by_task.values() if v)
    lines = [
        "# M0.2 — Segmentation gate",
        "",
        f"**{'PASS' if ok else 'FAIL'}** — `{result.source_document}` vs `{result.marking_scheme}`",
        "",
        f"- pandoc: `{pandoc_version()}`",
        f"- boilerplate strip: {strip_summary}",
        f"- chunks emitted: {chunk_count} ({parent_count} parents + "
        f"{chunk_count - parent_count} pointed leaf tasks)",
        "",
        "| | arkusz | marking scheme |",
        "|---|---|---|",
        f"| pointed tasks | {result.arkusz_task_count} | {result.marking_task_count} |",
        f"| total points | {result.arkusz_points_total} | {result.marking_points_total} |",
        "",
    ]
    if result.missing_in_arkusz:
        lines.append(f"- **in marking scheme but not arkusz:** {result.missing_in_arkusz}")
    if result.missing_in_marking:
        lines.append(f"- **in arkusz but not marking scheme:** {result.missing_in_marking}")
    if result.point_mismatches:
        lines.append(f"- **point mismatches (task, arkusz, marking):** {result.point_mismatches}")
    if ok:
        lines.append(
            "Counts and point values match exactly. Segmentation is trustworthy for "
            "this paper."
        )

    lines += [
        "",
        "## Figure completeness (SPEC: silent figure loss is a data error)",
        "",
        f"`<w:drawing>` in DOCX body: {fig_total} total — {fig_boilerplate} cover / "
        f"header / footer chrome, {fig_attributed} in {fig_regions} figure-bearing "
        "task region(s).",
        "",
    ]
    if incomplete:
        lines.append(
            f"**⚠ {len(incomplete)} chunk(s) expect a figure that was not extracted** "
            f"({fig_regions} own the figure, the rest inherit it via a parent stem). "
            "Pandoc drops Word-drawn shapes; extraction is M0.4. Until then every one "
            "of these is knowingly incomplete:"
        )
        lines.append("")
        lines.append("| task | expected | extracted |")
        lines.append("|---|---|---|")
        for c in incomplete:
            lines.append(
                f"| {c.exercise_number}{' (parent)' if c.is_parent else ''} "
                f"| {c.expected_figure_count} | {len(c.media_refs)} |"
            )
    else:
        lines.append("Every task's expected figure count is matched by an extracted asset.")

    if not result.marking_scheme_is_deterministic:
        lines += [
            "",
            "> Marking scheme was extracted from PDF (`pdftotext`), not a DOCX sibling "
            "(none exists). Deterministic for this born-digital Word PDF, but noted "
            "per the M0.1 exception.",
        ]
    lines.append("")
    path = OUT / "segmentation_gate.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def run() -> int:
    OUT.mkdir(exist_ok=True)
    WORK.mkdir(parents=True, exist_ok=True)

    # M0.1
    entries = build_corpus_split(MANIFEST, RAW)
    p1 = write_corpus_split(entries)
    print(f"M0.1  wrote {p1.relative_to(ROOT)}  ({len(entries)} documents)")

    # M0.2
    conv = convert_docx_to_latex(RAW / ARKUSZ_DOCX, WORK / "arkusz")
    body, strip_report = strip_boilerplate(conv.latex)
    fig_by_task, fig_boilerplate, fig_total = drawing_attribution(RAW / ARKUSZ_DOCX)
    chunks = segment_arkusz(
        body, source_document=ARKUSZ_DOCX, expected_figures=fig_by_task
    )

    seg_dir = OUT / "segmentation"
    seg_dir.mkdir(exist_ok=True)
    jsonl = seg_dir / f"{Path(ARKUSZ_DOCX).stem}.jsonl"
    jsonl.write_text(
        "\n".join(c.model_dump_json() for c in chunks) + "\n", encoding="utf-8"
    )

    marking = parse_marking_scheme(RAW / ZASADY_PDF)
    result = cross_validate(
        chunks,
        marking,
        source_document=ARKUSZ_DOCX,
        marking_scheme=ZASADY_PDF,
        marking_scheme_is_deterministic=False,
    )
    p2 = write_gate_report(
        result, chunks, strip_report.summary(), fig_by_task, fig_boilerplate, fig_total
    )
    incomplete = [c.exercise_number for c in chunks if c.figures_incomplete]
    print(f"M0.2  wrote {jsonl.relative_to(ROOT)}  ({len(chunks)} chunks)")
    print(f"M0.2  wrote {p2.relative_to(ROOT)}")
    print()
    print(f"  arkusz : {result.arkusz_task_count} tasks / {result.arkusz_points_total} pts")
    print(f"  marking: {result.marking_task_count} tasks / {result.marking_points_total} pts")
    print(f"  GATE   : {'PASS' if result.passed else 'FAIL'}")
    print(
        f"  figures: {len(incomplete)} chunk(s) missing an expected figure "
        f"(M0.4): {incomplete}"
    )
    if not result.passed:
        print(f"    missing_in_arkusz : {result.missing_in_arkusz}")
        print(f"    missing_in_marking: {result.missing_in_marking}")
        print(f"    point_mismatches  : {result.point_mismatches}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(run())
