"""Run the Track A batch and write m2/corpus_track_a_summary.md.

    uv run python -m zaspro.ingestion.batch_run

Needs the schema migrated and `sources` seeded first.
"""

from __future__ import annotations

import sys
from pathlib import Path

from zaspro.db.base import session_scope
from zaspro.ingestion.batch import ROOT, BatchSummary, run

OUT = ROOT / "m2" / "corpus_track_a_summary.md"

# Written after the fixing round: what actually had to change, vs what was
# predicted before the corpus arrived.
FIXING_NOTES = """\
**Nothing in `strip_boilerplate` or `segment_arkusz` needed changing.** The
maj-2024, maj-2025 and maj-2026 podstawowy czarnodruk papers are structurally
identical for both: same cover `\\begin{figure}` + three `longtable` blocks,
same `Zadanie N. (0--M)` / `Zadanie N.` / `Zadanie N.M. (0--M)` markers, same
`Koniec` sentinel, en-dash point markers rendered as `--`. The predicted
session-to-session drift (`a)`/`b)` subtasks, different point punctuation, a
moved sentinel) did not appear across these three.

Independently cross-checked: each arkusz's own cover states `Liczba punktów do
uzyskania: 46 / 50 / 50`, which matches both the segmented leaf-task point sum
and the `zasady` PDF total. The gate also matches every *individual* task's
point value, not just the totals.

**Marking-scheme name convention does vary and is handled.** maj-2025 ships a
czarnodruk `MMAP-P0-660-2505-zasady.pdf` (under a shared `zasady_oceniania/`
path upstream); 2024 and 2026 have only `MMAP-P0-100-{session}-zasady.pdf`.
`resolve_marking_scheme` drops the `-A`/`-B` and tries `660` then `100`. Since
all files land flat in `sources/raw/`, the upstream path move is irrelevant to
us.

**One real quality issue, not a correctness one: loose figure crops.** On
multiple sessions the vector-primitive crop keeps a few lines of the task's own
answer options above the figure (e.g. 2405 Zadanie 22). The figure itself is
always fully captured — every `render_status` is `complete`, `incomplete` is
empty — so it does not affect the gate. It is the M0.4 failure mode #4 (band
starts at the marker; plain-text lines with no primitives sit inside the box).
Tightening it is figure-quality work for when scene planning (M6) consumes the
crops; ADR 0004 item 4.
"""


def _fmt_report(r) -> str:
    if r is None:
        return ""
    return (
        f"{r.leaf_tasks} tasks / {r.points_total} pts / {r.exercises} exercises "
        f"({r.parents} parents); figures {r.figure_regions_rendered}/"
        f"{r.figure_regions_expected} regions, {r.figure_bearing_exercises} bearing, "
        f"incomplete {r.incomplete or 'none'}"
    )


def write_summary(summary: BatchSummary) -> Path:
    L = [
        "# Track A corpus — batch ingestion summary",
        "",
        "Generated by `zaspro.ingestion.batch_run`. Track A = CKE podstawowy exam "
        "papers with a `_660.docx` czarnodruk (version A only). Marking schemes "
        "are the `zasady` PDF for the session, czarnodruk name preferred.",
        "",
        "## Gate result per document",
        "",
        "| document | session | marking scheme | outcome | detail |",
        "|---|---|---|---|---|",
    ]
    for d in summary.docs:
        detail = _fmt_report(d.report) if d.outcome == "pass" else (d.reason or "")
        L.append(
            f"| `{d.file}` | {d.session} | "
            f"{('`' + d.marking_scheme + '`') if d.marking_scheme else '—'} "
            f"| **{d.outcome}** | {detail} |"
        )

    passed = [d for d in summary.docs if d.outcome == "pass" and d.report]
    L += [
        "",
        f"**{len(passed)}/{len(summary.docs)} documents pass the gate.**",
        "",
        "## Exercise and point counts",
        "",
        "| document | chunks | exercises | parents | leaf tasks | points |",
        "|---|---|---|---|---|---|",
    ]
    for d in passed:
        r = d.report
        L.append(
            f"| `{d.file}` | {r.chunks} | {r.exercises} | {r.parents} "
            f"| {r.leaf_tasks} | {r.points_total} |"
        )

    L += [
        "",
        "## Figure-bearing tasks across the corpus",
        "",
        "How much weight the Word-shape figure route carries.",
        "",
        "| document | figure regions | figure-bearing exercises | rendered | incomplete |",
        "|---|---|---|---|---|",
    ]
    tot_regions = tot_bearing = 0
    for d in passed:
        r = d.report
        tot_regions += r.figure_regions_expected
        tot_bearing += r.figure_bearing_exercises
        L.append(
            f"| `{d.file}` | {r.figure_regions_expected} | {r.figure_bearing_exercises} "
            f"| {r.figure_regions_rendered} | {r.incomplete or 'none'} |"
        )
    L.append(f"| **total** | **{tot_regions}** | **{tot_bearing}** | | |")

    L += [
        "",
        "## Informatory (not ingested — structural audit only)",
        "",
        "The informatory are theory + worked examples, not `Zadanie` lists, so "
        "the arkusz pipeline is not run against them. These numbers scope the "
        "separate semantic-chunking work.",
        "",
        "| document | oMath | display | drawings | Zadanie markers | Przykład markers |",
        "|---|---|---|---|---|---|",
    ]
    for a in summary.informatory:
        L.append(
            f"| `{a.file}` | {a.omath} | {a.omath_para} | {a.drawings} "
            f"| {a.zadanie_markers} | {a.przyklad_markers} |"
        )
    L += [
        "",
        "The `Zadanie` markers here are illustrative example tasks inside the "
        "prose (6 in pp, 32 in pr), not a scored paper — there is no marking "
        "scheme to cross-validate against, so the M0.2 hard gate does not apply. "
        "Semantic chunking needs to follow the informator's own heading structure "
        "(task-type descriptions, arkusz description, marking principles, worked "
        "examples) and assign `content_type` per chunk — that classification is "
        "review-queue / Ingestion-Agent territory (M3+), not deterministic Track "
        "A. Scoped as separate work; **not** attempted here and not counted as a "
        "Track A failure.",
    ]

    L += [
        "",
        "## Track B — registered, not ingested (ADR 0005)",
        "",
        f"{len(summary.track_b_registered)} documents given a `source_documents` row "
        "with `extraction_status = pending`:",
        "",
    ]
    for f in sorted(summary.track_b_registered):
        L.append(f"- `{f}`")

    L += [
        "",
        "## What the stripper / segmenter needed",
        "",
        FIXING_NOTES,
    ]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    return OUT


def main() -> int:
    with session_scope() as s:
        summary = run(s)
    path = write_summary(summary)

    print(f"Track A: {sum(d.outcome == 'pass' for d in summary.docs)}/{len(summary.docs)} pass")
    for d in summary.docs:
        print(f"  {d.outcome:18} {d.file}  {d.reason or ''}")
    print(f"informatory audited: {len(summary.informatory)}")
    print(f"Track B registered : {len(summary.track_b_registered)}")
    print(f"wrote {path}")
    return 0 if summary.all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
