"""Run the Track A batch and write m2/corpus_track_a_summary.md.

    uv run python -m zaspro.ingestion.batch_run

Needs the schema migrated and `sources` seeded first.
"""

from __future__ import annotations

import sys
from pathlib import Path

from zaspro.db.base import session_scope
from zaspro.ingestion.batch import ROOT, BatchSummary, run

OUT = ROOT / "m2" / "corpus_track_a_summary.md"

# Written after the fixing round over all seven Track A papers: what actually
# had to change, vs what was predicted.
FIXING_NOTES = """\
The corpus grew from three papers (maj 2024/2025/2026) to seven, adding four
pre-2024 sessions: **2305** (maj 2023), **2312** (grudzień 2023 diagnostyczny),
**2209** (wrzesień 2022 diagnostyczny), **2203** (marzec 2022 pokazowy). These
predate the settled Formuła 2023 exam format, so genuine variation was
expected. Here is what was actually hit.

**1. Czarnodruk DOCX naming (fixed, `zaspro.ingestion.batch`).** Two
conventions in the corpus: `MMAP-P0-660-A-2405-arkusz.docx` for sessions whose
PDF keeps the `-A/-B` letter, and `MMAP-P0-660-2305.docx` (no letter, no
`-arkusz` suffix) for the older sessions. `_ARKUSZ` now accepts both;
`persist._MMAP` likewise, and a missing letter leaves `paper_version` NULL
rather than defaulting it to `A`.

**2. Multi-variant marking-scheme PDFs (fixed, `resolve_marking_scheme` +
`marking_scheme` parser).** 2203/2209/2312 do not have a per-session
`MMAP-P0-100-{s}-zasady.pdf`; they ship one PDF whose name concatenates every
paper code, e.g. `MMAP-P0-100-200-300-400-660-700-Q00-2209-zasady.pdf`. The
resolver now globs `MMAP-{level}-*-{session}-zasady.pdf` and prefers a name
carrying a `660` token. Inside those PDFs subtasks are written `Zadanie 13.1
(0--1)` — **no period after the subtask number** — where the 2024+ format writes
`Zadanie 13.1. (0--1)`. The `_TASK_LINE` regex now treats that period as
optional. This is reading the oracle correctly, not loosening the gate; the
gate still demands an exact arkusz/marking-scheme match. That fix moved 2203
and 2312 from gate-fail to passing the task/point check.

**3. `strip_boilerplate` / `segment_arkusz`: still zero changes.** The predicted
drift (`a)`/`b)` subtasks, moved `Koniec`, different cover blocks) again did not
appear — all seven czarnodruk papers use the same `Zadanie N. (0--M)` /
`Zadanie N.M. (0--M)` markers, the same `Koniec` sentinel and the same
three-`longtable` cover. Segmentation of every paper matches that paper's own
cover point total (46 for 2203/2209/2305/2312/2405, 50 for 2505/2605).

**4. 2209 — genuine source defect, reported not worked around.** One marking-
scheme heading, `Zadanie 10.3.`, is missing the `(0--1)` range that all its
siblings (`10.1. (0--1)`, `10.2. (0--1)`) carry; the "Zasady oceniania" block
below it confirms 0--1. The arkusz is internally consistent (35 leaf tasks,
46 pts = its cover); the parser correctly enumerates 34 tasks / 45 pts from the
PDF. No range inference was added — a marking scheme that omits a machine-
readable point value for one subtask is a defect in that PDF and needs a hand
correction or a documented per-paper override, not a looser parser. **2209 does
not pass the gate.**

**5. 2312 — task-bearing raster/WMF figure, outside the WORD_SHAPE route.**
Zadanie 11.4 has a `<w:drawing>` the segmenter counts, but the DOCX carries it
as a raster/WMF asset (the file has image1.jpeg..image5.png + image3.wmf beside
its 94 `<wps:wsp>` vector shapes), so the `WORD_SHAPE` crop finds no vector
primitives in the task band and fails hard. The exercise is correctly flagged
incomplete. SPEC M2 kept `RASTER`/`WMF` as thin handlers on the assumption that
non-vector figures are page furniture in this corpus; 2312 breaks that
assumption. Productionising the raster/WMF route is separate work. **2312 does
not pass the figure-completeness gate.**

**Result: 5/7 pass clean. 2209 fails on a source-PDF defect (one subtask's
point range missing). 2312 fails on one raster/WMF task figure the WORD_SHAPE
route cannot crop.** Neither was hidden by relaxing the gate.
"""


def _fmt_report(r) -> str:
    if r is None:
        return ""
    return (
        f"{r.leaf_tasks} tasks / {r.points_total} pts / {r.exercises} exercises "
        f"({r.parents} parents); figures {r.figure_regions_rendered}/"
        f"{r.figure_regions_expected} regions, {r.figure_bearing_exercises} bearing, "
        f"incomplete {r.incomplete or 'none'}"
    )


def write_summary(summary: BatchSummary) -> Path:
    L = [
        "# Track A corpus — batch ingestion summary",
        "",
        "Generated by `zaspro.ingestion.batch_run`. Track A = CKE podstawowy exam "
        "papers with a `_660.docx` czarnodruk. Seven sessions: 2203, 2209, 2305, "
        "2312, 2405, 2505, 2605. Marking schemes are the `zasady` PDF for the "
        "session (czarnodruk name preferred; older sessions ship one "
        "concatenated-variant PDF, matched by the `660` token in its name).",
        "",
        "## Gate result per document",
        "",
        "| document | session | marking scheme | outcome | detail |",
        "|---|---|---|---|---|",
    ]
    for d in summary.docs:
        detail = _fmt_report(d.report) if d.outcome == "pass" else (d.reason or "")
        L.append(
            f"| `{d.file}` | {d.session} | "
            f"{('`' + d.marking_scheme + '`') if d.marking_scheme else '—'} "
            f"| **{d.outcome}** | {detail} |"
        )

    passed = [d for d in summary.docs if d.outcome == "pass" and d.report]
    L += [
        "",
        f"**{len(passed)}/{len(summary.docs)} documents pass the gate.**",
        "",
        "## Exercise and point counts",
        "",
        "| document | chunks | exercises | parents | leaf tasks | points |",
        "|---|---|---|---|---|---|",
    ]
    for d in passed:
        r = d.report
        L.append(
            f"| `{d.file}` | {r.chunks} | {r.exercises} | {r.parents} "
            f"| {r.leaf_tasks} | {r.points_total} |"
        )

    L += [
        "",
        "## Figure-bearing tasks across the corpus",
        "",
        "How much weight the Word-shape figure route carries.",
        "",
        "| document | figure regions | figure-bearing exercises | rendered | incomplete |",
        "|---|---|---|---|---|",
    ]
    tot_regions = tot_bearing = 0
    for d in passed:
        r = d.report
        tot_regions += r.figure_regions_expected
        tot_bearing += r.figure_bearing_exercises
        L.append(
            f"| `{d.file}` | {r.figure_regions_expected} | {r.figure_bearing_exercises} "
            f"| {r.figure_regions_rendered} | {r.incomplete or 'none'} |"
        )
    L.append(f"| **total** | **{tot_regions}** | **{tot_bearing}** | | |")

    L += [
        "",
        "## Informatory (not ingested — structural audit only)",
        "",
        "The informatory are theory + worked examples, not `Zadanie` lists, so "
        "the arkusz pipeline is not run against them. These numbers scope the "
        "separate semantic-chunking work.",
        "",
        "| document | oMath | display | drawings | Zadanie markers | Przykład markers |",
        "|---|---|---|---|---|---|",
    ]
    for a in summary.informatory:
        L.append(
            f"| `{a.file}` | {a.omath} | {a.omath_para} | {a.drawings} "
            f"| {a.zadanie_markers} | {a.przyklad_markers} |"
        )
    L += [
        "",
        "The `Zadanie` markers here are illustrative example tasks inside the "
        "prose (6 in pp, 32 in pr), not a scored paper — there is no marking "
        "scheme to cross-validate against, so the M0.2 hard gate does not apply. "
        "Semantic chunking needs to follow the informator's own heading structure "
        "(task-type descriptions, arkusz description, marking principles, worked "
        "examples) and assign `content_type` per chunk — that classification is "
        "review-queue / Ingestion-Agent territory (M3+), not deterministic Track "
        "A. Scoped as separate work; **not** attempted here and not counted as a "
        "Track A failure.",
    ]

    L += [
        "",
        "## Track B — registered, not ingested (ADR 0005)",
        "",
        f"{len(summary.track_b_registered)} documents given a `source_documents` row "
        "with `extraction_status = pending`:",
        "",
    ]
    for f in sorted(summary.track_b_registered):
        L.append(f"- `{f}`")

    L += [
        "",
        "## What the stripper / segmenter needed",
        "",
        FIXING_NOTES,
    ]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    return OUT


def main() -> int:
    with session_scope() as s:
        summary = run(s)
    path = write_summary(summary)

    print(f"Track A: {sum(d.outcome == 'pass' for d in summary.docs)}/{len(summary.docs)} pass")
    for d in summary.docs:
        print(f"  {d.outcome:18} {d.file}  {d.reason or ''}")
    print(f"informatory audited: {len(summary.informatory)}")
    print(f"Track B registered : {len(summary.track_b_registered)}")
    print(f"wrote {path}")
    return 0 if summary.all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
