"""Run the Track A batch and write m2/corpus_track_a_summary.md.

    uv run python -m zaspro.ingestion.batch_run

Needs the schema migrated and `sources` seeded first.
"""

from __future__ import annotations

import sys
from pathlib import Path

from zaspro.db.base import session_scope
from zaspro.ingestion.batch import ROOT, BatchSummary, run

OUT = ROOT / "m2" / "corpus_track_a_summary.md"

# Written after the fixing round over all seven Track A papers.
FIXING_NOTES = """\
The corpus grew from three papers (maj 2024/2025/2026) to seven, adding four
pre-Formuła-2023 sessions: **2305** (maj 2023), **2312** (grudzień 2023
diagnostyczny), **2209** (wrzesień 2022 diagnostyczny), **2203** (marzec 2022
pokazowy). **7/7 now pass.** What had to change was in the parsers and in two
hand-authored source-defect files, never in the gate.

**1. Czarnodruk DOCX naming (`zaspro.ingestion.batch`, `persist`).** Two
conventions: `MMAP-P0-660-A-2405-arkusz.docx` (keeps the `-A/-B` letter) and
the older `MMAP-P0-660-2305.docx` (no letter, no `-arkusz`). `_ARKUSZ` and
`_MMAP` accept both; a missing letter leaves `paper_version` NULL, never
defaulted to `A`.

**2. Multi-variant marking-scheme PDFs (`resolve_marking_scheme`,
`marking_scheme` parser).** 2203/2209/2312 ship one zasady PDF whose name
concatenates every paper code
(`MMAP-P0-100-200-300-400-660-700-Q00-2209-zasady.pdf`). The resolver globs
`MMAP-{level}-*-{session}-zasady.pdf`, preferring a `660` token. Inside those
PDFs subtasks are written `Zadanie 13.1 (0--1)` — no period after the number —
vs the 2024+ `Zadanie 13.1. (0--1)`; `_TASK_LINE` now treats that period as
optional. Reading the oracle correctly; the gate still demands an exact match.

**3. `strip_boilerplate` / `segment_arkusz`: still zero changes.** The predicted
drift (`a)`/`b)` subtasks, moved `Koniec`, different cover) did not appear in
any of the seven. Each paper's segmentation matches its own cover point total
(46 for 2203/2209/2305/2312/2405, 50 for 2505/2605).

**4. 2209 marking scheme — source defect, hand-corrected not inferred.** The
heading `Zadanie 10.3.` in the PDF is missing the `(0--1)` range every sibling
carries; the "Zasady oceniania" block below it confirms 0--1, and the arkusz's
own 46-pt cover total only reconciles with 10.3 = 1 pt. Recorded by hand in
`sources/marking_scheme_overrides.yaml` (with the page reference and the reason
it is a defect). The parser never infers a missing range — that would defeat
the check the gate exists to perform; it only applies a value a human entered.

**5. Three stray `<w:drawing>` elements, not figures
(`sources/figure_overrides.yaml`).** Re-checking every task drawing across all
seven papers (reusing the real marker walker): **every genuine exercise figure
is a `WORD_SHAPE`** — the earlier note that the older papers carried task
*raster* figures was a measurement error (a throwaway scan with a broken marker
regex misattributed chrome images to tasks). What the older papers do carry is
the occasional orphaned drawing group: 2209 Zadanie 10.1, 2312 Zadanie 11.4,
2605 Zadanie 32 each have a `<w:drawing>` with no text box, no image, only bare
connector/rectangle/line shapes, sitting in a "Dokończ zdanie" / multiple-
choice question that uses the parent's figure or needs none. Each is recorded
by hand with its corrected `expected_figure_count: 0`. `RASTER` and `WMF`
handlers stay wired to `source_format` for a future source; no exercise in this
corpus uses them.

**Result: 7/7 pass.** Two parser fixes (naming, multi-variant zasady), one
hand-entered marking-scheme correction (2209/10.3), three hand-entered
non-figure records (2209/10.1, 2312/11.4, 2605/32). The gate itself —
segmented arkusz must equal the marking scheme exactly, every substantive
figure linked and rendered — is unchanged.
"""


def _fmt_report(r) -> str:
    if r is None:
        return ""
    return (
        f"{r.leaf_tasks} tasks / {r.points_total} pts / {r.exercises} exercises "
        f"({r.parents} parents); figures {r.figure_regions_rendered}/"
        f"{r.figure_regions_expected} regions, {r.figure_bearing_exercises} bearing, "
        f"incomplete {r.incomplete or 'none'}"
    )


def write_summary(summary: BatchSummary) -> Path:
    L = [
        "# Track A corpus — batch ingestion summary",
        "",
        "Generated by `zaspro.ingestion.batch_run`. Track A = CKE podstawowy exam "
        "papers with a `_660.docx` czarnodruk. Seven sessions: 2203, 2209, 2305, "
        "2312, 2405, 2505, 2605. Marking schemes are the `zasady` PDF for the "
        "session (czarnodruk name preferred; older sessions ship one "
        "concatenated-variant PDF, matched by the `660` token in its name).",
        "",
        "## Gate result per document",
        "",
        "| document | session | marking scheme | outcome | detail |",
        "|---|---|---|---|---|",
    ]
    for d in summary.docs:
        detail = _fmt_report(d.report) if d.outcome == "pass" else (d.reason or "")
        L.append(
            f"| `{d.file}` | {d.session} | "
            f"{('`' + d.marking_scheme + '`') if d.marking_scheme else '—'} "
            f"| **{d.outcome}** | {detail} |"
        )

    passed = [d for d in summary.docs if d.outcome == "pass" and d.report]
    L += [
        "",
        f"**{len(passed)}/{len(summary.docs)} documents pass the gate.**",
        "",
        "## Exercise and point counts",
        "",
        "| document | chunks | exercises | parents | leaf tasks | points |",
        "|---|---|---|---|---|---|",
    ]
    for d in passed:
        r = d.report
        L.append(
            f"| `{d.file}` | {r.chunks} | {r.exercises} | {r.parents} "
            f"| {r.leaf_tasks} | {r.points_total} |"
        )

    L += [
        "",
        "## Figure-bearing tasks across the corpus",
        "",
        "How much weight the Word-shape figure route carries.",
        "",
        "| document | figure regions | figure-bearing exercises | rendered | incomplete |",
        "|---|---|---|---|---|",
    ]
    tot_regions = tot_bearing = 0
    for d in passed:
        r = d.report
        tot_regions += r.figure_regions_expected
        tot_bearing += r.figure_bearing_exercises
        L.append(
            f"| `{d.file}` | {r.figure_regions_expected} | {r.figure_bearing_exercises} "
            f"| {r.figure_regions_rendered} | {r.incomplete or 'none'} |"
        )
    L.append(f"| **total** | **{tot_regions}** | **{tot_bearing}** | | |")

    L += [
        "",
        "## Informatory (not ingested — structural audit only)",
        "",
        "The informatory are theory + worked examples, not `Zadanie` lists, so "
        "the arkusz pipeline is not run against them. These numbers scope the "
        "separate semantic-chunking work.",
        "",
        "| document | oMath | display | drawings | Zadanie markers | Przykład markers |",
        "|---|---|---|---|---|---|",
    ]
    for a in summary.informatory:
        L.append(
            f"| `{a.file}` | {a.omath} | {a.omath_para} | {a.drawings} "
            f"| {a.zadanie_markers} | {a.przyklad_markers} |"
        )
    L += [
        "",
        "The `Zadanie` markers here are illustrative example tasks inside the "
        "prose (6 in pp, 32 in pr), not a scored paper — there is no marking "
        "scheme to cross-validate against, so the M0.2 hard gate does not apply. "
        "Semantic chunking needs to follow the informator's own heading structure "
        "(task-type descriptions, arkusz description, marking principles, worked "
        "examples) and assign `content_type` per chunk — that classification is "
        "review-queue / Ingestion-Agent territory (M3+), not deterministic Track "
        "A. Scoped as separate work; **not** attempted here and not counted as a "
        "Track A failure.",
    ]

    L += [
        "",
        "## Track B — registered, not ingested (ADR 0005)",
        "",
        f"{len(summary.track_b_registered)} documents given a `source_documents` row "
        "with `extraction_status = pending`:",
        "",
    ]
    for f in sorted(summary.track_b_registered):
        L.append(f"- `{f}`")

    L += [
        "",
        "## What the stripper / segmenter needed",
        "",
        FIXING_NOTES,
    ]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    return OUT


def main() -> int:
    with session_scope() as s:
        summary = run(s)
    path = write_summary(summary)

    print(f"Track A: {sum(d.outcome == 'pass' for d in summary.docs)}/{len(summary.docs)} pass")
    for d in summary.docs:
        print(f"  {d.outcome:18} {d.file}  {d.reason or ''}")
    print(f"informatory audited: {len(summary.informatory)}")
    print(f"Track B registered : {len(summary.track_b_registered)}")
    print(f"wrote {path}")
    return 0 if summary.all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
