"""Write m3/mapping_calibration.md from the recorded review decisions.

    uv run python -m zaspro.review.calibration_run

Run it after a calibration pass (map one arkusz with `--review-all`, then work
the queue by keyboard).
"""

from __future__ import annotations

import sys
from pathlib import Path

from zaspro.db.base import session_scope
from zaspro.review.calibration import agreement_curve

OUT = Path(__file__).resolve().parents[3] / "m3" / "mapping_calibration.md"


def render() -> str:
    with session_scope() as s:
        cal = agreement_curve(s)

    L = [
        "# Mapping agent — agreement vs confidence",
        "",
        "How often the reviewer accepted the agent's mapping **unchanged**, by "
        "the agent's own confidence band. This is what `AUTO_APPROVE_THRESHOLD` "
        "should be set from (ADR 0009). Generated by "
        "`zaspro.review.calibration_run`.",
        "",
        f"Resolved mapping reviews: **{cal.resolved}**  ·  still open: {cal.pending}  "
        f"·  target agreement: {cal.target:.0%}",
        "",
        "| confidence band | n | accepted unchanged | changed/rejected | agreement | (of n) audit-sampled |",
        "|---|---|---|---|---|---|",
    ]
    for b in cal.bands:
        rate = f"{b.agreement:.0%}" if b.agreement is not None else "—"
        L.append(
            f"| [{b.lo:.1f}, {b.hi:.1f}){' ' if b.hi < 1 else ']'} | {b.n} | "
            f"{b.agree} | {b.disagree} | {rate} | {b.audit} |"
        )

    L += [""]
    if cal.recommended_threshold is not None:
        L.append(
            f"**Evidence-based threshold: {cal.recommended_threshold:.2f}** — the "
            f"lowest band at/above which every band clears {cal.target:.0%} "
            "agreement (with ≥5 samples). Set `AUTO_APPROVE_THRESHOLD` here."
        )
    else:
        L.append(
            "**No threshold recommendation yet** — not enough resolved reviews, or "
            "no confidence band clears the target. Keep the queue at "
            "`--review-all` and work more mappings."
        )
    for n in cal.notes:
        L.append(f"- {n}")
    L.append("")
    return "\n".join(L)


def main() -> int:
    OUT.parent.mkdir(exist_ok=True)
    text = render()
    OUT.write_text(text, encoding="utf-8")
    print(text)
    print(f"\nwrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
